{% set version = "2.13" %}

package:
  name: spot
  version: {{ version }}

source:
  url: https://www.lre.epita.fr/dload/spot/spot-{{ version }}.tar.gz
  sha256: 0d0fe673cf1bc8933727bc8e0be7ba36901445211e2945ac73fb09835c81f4eb

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - graphviz

test:
  imports:
    - spot
    - spot.gen
    - spot.aux
    - spot.ltsmin
    - buddy
  commands:
    - test {{ version }} = "`python -c 'import spot; print(spot.version())'`"

about:
  home: https://spot.lre.epita.fr
  license: GPL-3.0-or-later
  license_file: debian/copyright
  summary: Platform for manipulation of LTL formulas and ω-automata.
  description: |
    Spot is a C++17 library for LTL, ω-automata manipulation, and model
    checking.  It also comes with a Python interface, and command-line
    tools.
  doc_url: https://spot.lre.epita.fr/
  dev_url: https://gitlab.lre.epita.fr/spot/spot/

extra:
  recipe-maintainers:
    - adl
