{% set version = "2.10.2" %}

package:
  name: spot
  version: {{ version }}

source:
  url: http://www.lrde.epita.fr/dload/spot/spot-{{ version }}.tar.gz
  sha256: c1c4ba4f1c87919b3d2749280c7e9959a7d82a4a43a97a19eca0a3ca22605066

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - graphviz

test:
  imports:
    - spot
    - spot.gen
    - spot.aux
    - spot.ltsmin
    - buddy
  commands:
    - test {{ version }} = "`python -c 'import spot; print(spot.version())'`"

about:
  home: https://spot.lrde.epita.fr
  license: GPL-3.0-or-later
  license_file: debian/copyright
  summary: Platform for manipulation of LTL formulas and ω-automata.
  description: |
    Spot is a C++17 library for LTL, ω-automata manipulation, and model
    checking.  It also comes with a Python interface, and command-line
    tools.
  doc_url: https://spot.lrde.epita.fr/
  dev_url: https://gitlab.lrde.epita.fr/spot/spot/

extra:
  recipe-maintainers:
    - adl
